Fix Pipeline and check for PHP 8 / 8.1 support
reactphp-inspector/memory-usage pull request #19
Opened 2021-11-03 13:34 UTC by fritz-gerneth

2021-11-03 19:50 UTC, WyriHaximus requested changes
Awesome! I just have a tiny change request so it's easier to see at first glance how the pipeline ran.

2021-11-03 19:50 UTC, WyriHaximus commented on .github/workflows/ci.yml
>        matrix:
```suggestion
      fail-fast: false
      matrix:
```

2021-11-04 11:45 UTC, fritz-gerneth commented
All green now

2021-11-07 09:43 UTC, WyriHaximus approved these changes

2021-11-07 09:45 UTC, merged